version: '3.2'

services:
  sqmail:
    build:
      args:
        - SQMAIL_TAG=${SQMAIL_TAG}
        - FEHQLIBS_TAG=${FEHQLIBS_TAG}
        - DAEMONTOOLS_TAG=${DAEMONTOOLS_TAG}
        - UCSPISSL_TAG=${UCSPISSL_TAG}
        - UCSPITCP6_TAG=${UCSPITCP6_TAG}
        - DOVECOT_TAG=${DOVECOT_TAG}
        - CLAMAV_TAG=${CLAMAV_TAG}
        - SPAMASSASSIN_TAG=${SPAMASSASSIN_TAG}
        - FCRON_TAG=${FCRON_TAG}
    image: semhoun/sqmail:${SQMAIL_VERSION}
    volumes:
      - ./data/qcontrol:/var/qmail/control
      - ./data/ssl:/ssl
      - ./data/domains:/var/vpopmail/domains
      - ./data/vpopmail_etc:/var/vpopmail/etc
      - ./data/log:/log
      - ./data/spamassassin:/var/spamassassin
      - ./data/tmp:/var/qmail/tmp
      - ./data/qusers:/var/qmail/users
    ports:
      - 8090:80
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
