version: "3.2"

services:
    sqmail:
        build:
            args:
                - SQMAIL_TAG=${SQMAIL_TAG}
                - FEHQLIBS_TAG=${FEHQLIBS_TAG}
                - DAEMONTOOLS_TAG=${DAEMONTOOLS_TAG}
                - UCSPISSL_TAG=${UCSPISSL_TAG}
                - UCSPITCP6_TAG=${UCSPITCP6_TAG}
                - DOVECOT_TAG=${DOVECOT_TAG}
                - CLAMAV_TAG=${CLAMAV_TAG}
                - SPAMASSASSIN_TAG=${SPAMASSASSIN_TAG}
                - FCRON_TAG=${FCRON_TAG}
        image: semhoun/sqmail:${SQMAIL_VERSION}
        environment:
            - QMAIL_NB_REMOTE=5
            - QMAIL_NB_INCOMING=50
            - VPOPMAIL_QUOTA=1073741824
            - VPOPMAIL_MYSQL_HOST=mariadb
            - VPOPMAIL_MYSQL_DB=vpopmail
            - VPOPMAIL_MYSQL_USER=vpopmail
            - VPOPMAIL_MYSQL_PASS=vpopmail_pwd
            - VPOPMAIL_DEFAULT_DOMAIN=semhoun.net
        volumes:
            - ../mail_data/qcontrol:/var/qmail/control
            - ../mail_data/ssl:/ssl
            - ../mail_data/domains:/var/vpopmail/domains
            - ../mail_data/vpopmail_etc:/var/vpopmail/etc
            - ../mail_data/log:/log
            - ../mail_data/spamassassin:/var/spamassassin
            - ../mail_data/tmp:/var/qmail/tmp
            - ../mail_data/qusers:/var/qmail/users
        ports:
            - 8090:80
            - 25:25
            - 465:465
            - 587:587
            - 110:110
            - 995:995
            - 143:143
            - 993:993
        depends_on:
            - mariadb
            
    mariadb:
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb_root
            - MARIADB_DATABASE=vpopmail
            - MYSQL_USER=vpopmail
            - MYSQL_PASSWORD=vpopmail_pwd
        volumes:
            - ../mail_data/mariadb:/var/lib/mysql

    adminer:
        image: adminer
        depends_on:
            - mariadb
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: mariadb
            ADMINER_DEFAULT_DB_NAME: vpopmail
            ADMINER_DESIGN: nette
            ADMINER_PLUGINS: tables-filter tinymce
        restart: always
        ports:
            - 8091:8080
