version: '3.2'

services:
  sqmail-aio:
    build:
      args:
        - SQMAIL_TAG=${SQMAIL_TAG}
        - FEHQLIBS_TAG=${FEHQLIBS_TAG}
        - EXECLINE_TAG=${EXECLINE_TAG}
        - SKALIB_TAG=${SKALIB_TAG}
        - S6_TAG=${S6_TAG}
        - UCSPISSL_TAG=${UCSPISSL_TAG}
        - UCSPITCP6_TAG=${UCSPITCP6_TAG}
        - DOVECOT_TAG=${DOVECOT_TAG}
        - DOVECOT_PIGEONHOLE_TAG=${DOVECOT_PIGEONHOLE_TAG}
        - CLAMAV_TAG=${CLAMAV_TAG}
        - SPAMASSASSIN_TAG=${SPAMASSASSIN_TAG}
        - FCRON_TAG=${FCRON_TAG}
        - ROUNDCUBEMAIL_TAG=${ROUNDCUBEMAIL_TAG}
        - VPOPMAIL_TAG=${VPOPMAIL_TAG}
        - ACMESH_TAG=${ACMESH_TAG}
        - QMAILADMIN_TAG=${QMAILADMIN_TAG}
        - VQADMIN_TAG=${VQADMIN_TAG}
    network_mode: bridge
    extra_hosts:
      - mariadb:host-gateway
    environment:
      - DEV_MODE=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sqmail.rule=Host(`mail.dune.tf`)"
      - "traefik.http.routers.sqmail.entryPoints=websecure"
      - "traefik.http.routers.sqmail.tls.certresolver=le-dns"
      - "traefik.http.routers.sqmail.service=sqmail"
      - "traefik.http.services.sqmail.loadbalancer.server.port=80"
      - "traefik.http.routers.sqmail_acme.rule=Host(`mail.dune.tf`) && PathPrefix(`/.well-known/acme-challenge/`)"
      - "traefik.http.routers.sqmail_acme.entryPoints=web"
      - "traefik.http.routers.sqmail_acme.priority=9000" 
      - "traefik.http.routers.sqmail_acme.service=sqmail_acme"
      - "traefik.http.services.sqmail_acme.loadbalancer.server.port=80" 
    image: semhoun/sqmail_all-in-one:${SQMAIL_AIO_VERSION}
    volumes:
      - ./data/qcontrol:/var/qmail/control
      - ./data/ssl:/ssl
      - ./data/domains:/var/vpopmail/domains
      - ./data/vpopmail_etc:/var/vpopmail/etc
      - ./data/log:/log
      - ./data/spamassassin:/var/spamassassin
      - ./data/tmp:/var/qmail/tmp
      - ./data/qusers:/var/qmail/users
      - ./data/queue:/var/qmail/queue
      - ./data/alias:/var/qmail/alias
      - ./data/domainkeys:/var/qmail/ssl/domainkeys
    ports:
      - 8090:80
      - 8091:443
      - 8092:88
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
