version: '3.2'

services:
  qmail-aio:
    build:
      args:
        - SQMAIL_TAG=${SQMAIL_TAG}
        - FEHQLIBS_TAG=${FEHQLIBS_TAG}
        - EXECLINE_TAG=${EXECLINE_TAG}
        - SKALIB_TAG=${SKALIB_TAG}
        - S6_TAG=${S6_TAG}
        - UCSPISSL_TAG=${UCSPISSL_TAG}
        - UCSPITCP6_TAG=${UCSPITCP6_TAG}
        - DOVECOT_TAG=${DOVECOT_TAG}
        - CLAMAV_TAG=${CLAMAV_TAG}
        - SPAMASSASSIN_TAG=${SPAMASSASSIN_TAG}
        - FCRON_TAG=${FCRON_TAG}
    extra_hosts:
      - mariadb:host-gateway
    environment:
      - DEV_MODE=1
    image: semhoun/qmail_all-in-one:${QMAIL_AIO_VERSION}
    volumes:
      - ./data/qcontrol:/var/qmail/control
      - ./data/ssl:/ssl
      - ./data/domains:/var/vpopmail/domains
      - ./data/vpopmail_etc:/var/vpopmail/etc
      - ./data/log:/log
      - ./data/spamassassin:/var/spamassassin
      - ./data/tmp:/var/qmail/tmp
      - ./data/qusers:/var/qmail/users
      - ./data/queue:/var/qmail/queue
      - ./data/alias:/var/qmail/alias
    ports:
      - 8090:80
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
