name: docker

on: # specify the build to trigger the automated ci/cd
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest # specify the build machine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            semhoun/sqmail_all-in-one       
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SQMAIL_TAG
            FEHQLIBS_TAG
            EXECLINE_TAG
            SKALIB_TAG
            S6_TAG
            UCSPISSL_TAG
            UCSPITCP6_TAG
            DOVECOT_TAG
            DOVECOT_PIGEONHOLE_TAG
            CLAMAV_TAG
            SPAMASSASSIN_TAG
            FCRON_TAG
            ROUNDCUBEMAIL_TAG
            VPOPMAIL_TAG
            ACMESH_TAG
            QMAILADMIN_TAG
            VQADMIN_TAG
